name: Build and Execute Python Script

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         python-version: ['3.11','3.10']

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installation des d√©pendances
        run: pip install fastapi locust pytest uvicorn coverage httpx pytest-mock pytest-profiling pylint sqlalchemy pydantic

      - name: Execution des tests
        run: coverage run -m pytest; coverage xml
      
      - name: Get Coverage - change
        uses: orgoro/coverage@v3.1
        with:
            coverageFile: coverage.xml
            token: ${{secrets.EPSI_TOKEN}}