name: Build and Execute Python Script

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkoout du code
        uses: actions/checkout@v4

      - name: Istallation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ex√©cution du script Python
        run: python main.py